fix /bin/wslpath missing
nix-community/NixOS-WSL pull request #106
Opened 2022-06-13 17:30 UTC by nzbr

2022-06-14 17:13 UTC, SuperSandro2000 requested changes
That only kinda works when doing ``PATH=$PATH:/bin code .``

NixOS does not include ``/bin`` into ``$PATH`` by default but adding it is also not necessary since wslpath only cares about the symlink name, not the path. So it should be enough to create a basic package which symlinks /init to ``$out/bin/wslpath``

2022-06-14 17:16 UTC, SuperSandro2000 commented
something like this

```nix
environment.systemPackages = [
(pkgs.writeShellScript "wslpath" ''
  ln -rs /init $out/bin/wslpath
'';)
];
```

2022-06-16 17:13 UTC, SuperSandro2000 commented on modules/wsl-distro.nix
> +            ln -rs /init $out/bin/wslpath
```suggestion
            ln -s /init $out/bin/wslpath
```

We don't want a relative symlink here.

2022-06-19 12:13 UTC, nzbr commented on modules/wsl-distro.nix
> +        '';
/bin/sh and /bin/mount get created when the rootfs tarball is created. They are needed for WSL to work correctly, so linking them to the version from the current nixpkgs is probably a good idea anyway. Having a /bin/wslpath probably won't hurt as well

2022-06-19 18:30 UTC, SuperSandro2000 commented on modules/wsl-distro.nix
> +        '';
Yeah, true. Not that important tbh.

2022-06-20 09:37 UTC, merged