Add DistroLauncher
nix-community/NixOS-WSL pull request #320
Opened 2023-10-29 08:50 UTC by nzbr

This PR is a continuation of #94, which I had to close because GitHub does not allow changing a PR's source branch once it has been created. Please look there for all previous discussion.

Add a custom DistroLauncher. This will allow packaging NixOS-WSL as an MSIX package and upload it to the MS Store eventually

This is a custom reimplementation of DistroLauncher in C# (instead of C++, which is what the reference implementation uses)
The rewrite gives us greater flexibility in extending the DistroLauncher with additional features, e.g. upgrading to newer releases of NixOS-WSL with something like `nixos update`

- [x] Fix WslLaunchInteractive return codes
- [x] Updating works
- [x] systemd implementation in version output
- [x] Update.cs: Use mktemp instead of a hard-coded directory
- [ ] Check for nixos-unstable channel before overwriting it
- [ ] Make secrets more easily accessible by using something like age or sops
- [ ] Put a decryption key into the repo secrets

_Future ideas_
- [ ] Rescue Shell
- [ ] Rollback
- [ ] Updating to specific git revisions instead of the bundled tarball's version

Related: #63 #78

2023-12-13 23:45 UTC, rogusdev commented
Is this still being worked on, or has it been dropped in favor of something else? If it's still underway, is there any particular way to help / instructions url from MS on what needs to happen for remaining steps or anything? Thanks :)

2023-12-23 00:24 UTC, nzbr commented
It's still underway. It was on hold because we moved to loading the wsl-module from a channel instead of `/etc/nixos/nixos-wsl`, meaning that I'd have to reimplement the updater included in the launcher. I should probably just rip it out for now and reimplement it later, when I have more time for it, so that we can at least have the launcher merged. Once the launcher is merged, it, from what I understand, in theory be possible to push the resulting `.msixbundle` onto the MS store

2024-01-11 16:10 UTC, thexyno requested changes
don't have any knowledge about windows internals, but looks good all in all

2024-01-11 16:10 UTC, thexyno commented on Launcher/Launcher/src/Helpers/VersionHelper.cs
> +    public static Version? LauncherVersion => Assembly.GetEntryAssembly()?.GetName().Version;
```suggestion
    public static Version? LauncherVersion => type(VersionHelper).Assembly.GetName().Version;
```

see https://learn.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getexecutingassembly?view=net-8.0&redirectedfrom=MSDN#remarks

2024-01-11 16:10 UTC, thexyno commented on Launcher/Launcher/src/WSL/Kernel32/CloseHandle.cs
> +}
noeol here?

2024-01-11 16:10 UTC, thexyno commented on Launcher/default.nix
> +  };
It is currently recommended to use `hash` and not `sha256` for anything nixpkgs related 

https://nixos.org/manual/nixpkgs/stable/#fetchurl

2024-01-11 17:12 UTC, merged