Add modules/vscode-remote-wsl-extension-workaround.nix (fix #238)
nix-community/NixOS-WSL pull request #324
Opened 2023-11-03 04:41 UTC by Atry

This PR adds `modules/vscode-remote-wsl-extension-workaround.nix` to fix #238

2023-11-03 16:41 UTC, K900 commented
I would prefer to see something like https://github.com/K900/vscode-remote-workaround, which simply uses nixpkgs node.js

2023-11-08 01:45 UTC, Atry commented
This PR is technically not a workaround. It just provides what vscode-server assumes (global C runtime and global coreutils).

2023-11-08 03:29 UTC, K900 commented
Then neither is my approach, because it provides a functioning Node runtime.

2023-11-08 04:45 UTC, Atry commented
But it replaces vscode’s node on fly, right?

On Tue, Nov 7, 2023 at 7:29 PM K900 ***@***.***> wrote:

> Then neither is my approach, because it provides a functioning Node
> runtime.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nix-community/NixOS-WSL/pull/324#issuecomment-1800954373>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAES3OVQE52LJSADH3D26ELYDL4CRAVCNFSM6AAAAAA634FOO6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMBQHE2TIMZXGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-11-08 06:50 UTC, K900 commented
Correct.

2023-11-09 00:34 UTC, SuperSandro2000 requested changes
Since this affects every program and can cause unexpected regressions I am very reluctant to accept it, especially regarding that we would still need an older WSL release which is probably a separate problem but is helping the situation not.

2023-11-10 18:03 UTC, Atry commented
Since you are reluctant to accept this PR. I just put it in a separate repository and close this PR.

Feel free to use this module from https://github.com/Atry/nixos-wsl-vscode

2023-11-10 18:03 UTC, closed without merging